### ISSUE TITLE
open as floating window

### ISSUE THREAD

**Issue by juantascon** [SidOfc/carbon.nvim#1]
can you open Carbon as a floating window similar to telescope or fzf?

**Comment by SidOfc** [comment]
Not natively as in, there is no `:Fcarbon` command to spawn a floating instance, that said, this can easily be achieved by making a floating window yourself, making that the current window, and then executing `normal! Carbon` to show Carbon in your newly created floating window.

Is this something you would be willing to try to do yourself and potentially create a PR for it?

**Comment by SidOfc** [comment]
Hello @juantascon, I've added a new `Fcarbon` command which will now spawn a floating window. See `:h Fcarbon` for more information.
