### ISSUE TITLE
Handling symlink to a directory

### ISSUE THREAD

**Issue by saccarosium** [SidOfc/carbon.nvim#102]
Hi,
currently a symlink pointing to a directory is treated as a file and not a directory. There are plans to support handling of symlinked directories?

https://user-images.githubusercontent.com/96259932/203868602-e8421d54-5729-49d2-bdcf-551f1b317cff.mov

**Comment by SidOfc** [comment]
That's a bug, will check it out when I have some time 👍

**Comment by SidOfc** [comment]
Hello again @saccarosium, I believe I've found and fixed the issue in branch [`patch/buffer/symlink-status`](https://github.com/SidOfc/carbon.nvim/tree/patch/buffer/symlink-status), would you mind giving it a spin to confirm?

**Comment by saccarosium** [comment]
I've just tried it and it works all fine.

**Comment by SidOfc** [comment]
Thanks, fix has been merged 👍
