### ISSUE TITLE
Disable changing of the cursor shape when open with `carbon-util-confirm`

### ISSUE THREAD

**Issue by saccarosium** [SidOfc/carbon.nvim#107]
Hi,
There is this thing that is bothering me with the changing of the cursor shape. When I enter the prompt for `carbon-util-confirm` the cursor change to an underline and remane like that for all the shell session. I would be really nice having an option in the setting for disabling this behaviour.

https://user-images.githubusercontent.com/96259932/206923297-62acc267-547c-4cac-bff6-d93794d1799f.mov

**Comment by SidOfc** [comment]
Fair enough, I can imagine one wanting to see the regular cursor in such windows, I may actually remove that part all together since I don't think it provides much value 👍

**Comment by SidOfc** [comment]
#108 resolves this, I also defaulted `Normal` in this popup to use the same highlight group as the border and cursor line since by default it looked a bit confusing in menus with only 2 entries.

Cheers for the report 👍
