### ISSUE TITLE
Missing BufAdd / VimEnter mapping

### ISSUE THREAD

**Issue by kaihowl** [SidOfc/carbon.nvim#126]
When not keeping netrw, carbon will add its own versions of `Explore` et al. What is not added are the `BufAdd` and `VimEnter` autocommands that check if the about to be created buffer is a directory. If so, then show the file tree instead.

Without this calling `:e . <cr>` will not show a directory listing of the current working directory. Instead, an empty buffer will be shown.

While trying to implement this behavior, I ran into the issue that there really only is a single Carbon buffer at all times. Switching the buffer as part of the `BufAdd` event seems not possible and would possibly be strange.

Is there a way to achieve this or would this require to extend Carbon with more than just a single buffer?

**Comment by SidOfc** [comment]
I've actually been working on this already in a branch, but master has moved on as well so I need to merge the two diverging branches and ensure all features keep working before creating a new release.

Since it will require some proper attention I'm not sure exactly when I'll do this since the branches differ quite a bit now. I'll try to put some effort into this the coming weeks.

**Comment by SidOfc** [comment]
Hello again, I've updated the `insanity` branch so it's once again up to date with latest `master`. This means using the branch should work the same as master in addition to features implemented in the `insanity` branch alone.

What remains now is to document all the changes which I will try to do soon though it might still take a while. In the meantime `insanity` branch should be up to date and functional :)

**Comment by kaihowl** [comment]
Hey there, I tested the branch again and observed the following:

- Open nvim, call `:edit .`.
- Open any file in the current working directory directly with `:edit subfolder/something.txt`.
- Call `:Explore!`.

Expected: file is revealed recursively (as happens in `master`).

Actual: file is not revealed and cursor is set to the first line of the tree.

Again, thank you very much for pouring time into this. Very much appreciated. :)

**Comment by SidOfc** [comment]
Cheers for the repro, in the branch the buffer lines get cached, when expanding to show a path, this cache did not get busted yet. It's been patched :)

**Comment by KaiHoewelmeyer-TomTom** [comment]
Thanks for the quick fix! I tried it out and can confirm that this works nicely.

**Comment by kaihowl** [comment]
Thanks for the quick fix! I tried it out and can confirm that this works nicely.

**Comment by yebt** [comment]
Hi, I try to solve this with  lazy.nvim package manager.
Inside the `init` call,  apply a function to call  explore carbon function `require('carbon').explore()` if the buffer is a directory
```lua
{
"SidOfc/carbon.nvim",
lazy = true,
event = "BufEnter",
init = function()
	vim.g.carbon_lazy_init = true
	 if vim.fn.argc() == 1 then
	 	local stat = vim.loop.fs_stat(vim.fn.argv(0))
	 	if stat and stat.type == "directory" then
			require('carbon').explore()
	 	end
	 end
end,
config = function()
	local carbon = require("carbon")
	carbon.setup({
		--  carbon settings
                      })
end,
},

```

**Comment by SidOfc** [comment]
Hello @kaihowl, latest release has been merged. It is a breaking release so I would advise checking out the release here: https://github.com/SidOfc/carbon.nvim/releases/tag/0.19.0.

Considering this branch I've been working on for a while has been merged and includes the feature requested in this issue I think this can be closed unless some unforeseen issue pops up. Can you confirm this issue has been resolved?

**Comment by kaihowl** [comment]
Hey there, @SidOfc:
I took the master branch for another spin and it seems to work very nicely.

Thank you once more for making this happen. :)

The issue can of course be closed. I didn't not spot any sponsorship options on this project / your profile. Let me know how I can buy you a beverage virtually for all your effort.

**Comment by SidOfc** [comment]
Glad to hear it's working well so far. Already had the code working in the branch I mentioned before but yeah, lots of documentation to migrate which was just a bit daunting. I would have gotten to it at some point but users in need provide some extra motivation :)

I don't really expect any payment for this kind of work either. The money would be better off at a charity organisation I reckon however I do have a [PayPal donation](https://www.paypal.com/donate/?hosted_button_id=RSE95KHD39CVN) link if you feel strongly about it :)

Cheers for the feedback and kindness and have a good one!
