### ISSUE TITLE
Add mapping to toggle show/hide of excluded files

### ISSUE THREAD

**Issue by ironsigma** [SidOfc/carbon.nvim#132]
Add mapping to toggle show/hide of excluded files

**Comment by ironsigma** [comment]
I was able to add a key map to a function and saved the current exclude list to a temp variable and set `settings.exclude` to `nil`, but couldn't figure out how to trigger a full refresh.

**Comment by SidOfc** [comment]
Hello @ironsigma, I've also just implemented this feature. Hidden files and directories are now treated as regular entries except they just won't be rendered. See `:h carbon-setting-actions-toggle-hidden`.

Similar to #131 I'm going to close this but feel free to reopen if I missed something.

**Comment by ironsigma** [comment]
Very nice, than you.

**Comment by SidOfc** [comment]
This was a good suggestion, regular file explorers also have the ability to toggle such behavior :)
