### ISSUE TITLE
Default float width is very narrow

### ISSUE THREAD

**Issue by Ansimorph** [SidOfc/carbon.nvim#139]
This is my personal experience, so feel free to dismiss this if it only affects me:
When working with projects with deeply nested files or long filenames, 40 characters is not a lot of width for the floating window.

The floating windows of other plugins are usually much wider. I would suggest increasing the default width to
`local width = math.min(80, math.floor(columns * 0.9))`

**Comment by SidOfc** [comment]
No that sounds like quite a fair improvement, at most 90% of screen real estate will be taken up so doubling the default dimensions seems fine. I've already published a new release with this change, in addition to width the height is also doubled.

Cheers for the report 👍

**Comment by Ansimorph** [comment]
Thanks!
