### ISSUE TITLE
Mapping for closing the current open node

### ISSUE THREAD

**Issue by saccarosium** [SidOfc/carbon.nvim#93]
Hi,
I've been using the plugin for a few days and I would like a to a have a way too toggle the node without moving the cursor up to the parent directory.

## Current behavior 
```
Dir <-- cursor is here

press default edit command (<CR>)

Dir
  file1
  file2 <-- I move here 
  file3

If I want to close back the node I have to go up to dir and repress enter to close it. 
```

## Wanted behavior 
```
Dir <-- cursor is here

press default edit command (<CR>)

Dir
  file1
  file2 <-- I move here 
  file3

I press my preferred keybinding from file2 and the node closes.
```

**Comment by SidOfc** [comment]
Sounds like a nice feature to have indeed and should not be too difficult to implement.
Additionally, I think it is nice if this works with counts too, so you can close one or more levels of nesting at once.

Cheers, will look into this soonish 👍

**Comment by SidOfc** [comment]
Just implemented the base feature in a branch called [feature/close-dir-from-cursor-position](https://github.com/SidOfc/carbon.nvim/tree/feature/close-dir-from-cursor-position).

Undocumented and untested so not ready to merge yet, but if I'd like to give it a spin you can. The action is mapped to <kbd>-</kbd> by default, and can optionally be prefixed with a count i.e. <kbd>2</kbd><kbd>-</kbd> will close the next 2 collapsible parent entries.

**Comment by saccarosium** [comment]
I'm testing it and works like a charm! If I found any bug I will let you know.
